### ISSUE TITLE
[Enhancement] Enhance Documentation

### ISSUE THREAD

**Issue by suryanshsingh2001** [suryanshsingh2001/mockly#10]
**Description:**  
We need to improve the documentation for the project to ensure it's comprehensive and user-friendly. This will help new contributors and users better understand how to use and contribute to the project.

**Tasks:**

- [ ] Review existing documentation for clarity and completeness
- [ ] Add examples for key features
- [ ] Improve setup instructions
- [ ] Create a FAQ section for common issues
- [ ] Ensure all code snippets are correct and up-to-date

**Comment by pchy-ynda** [comment]
Hello! I'd like to take on this task, can you please assign it to me?

**Comment by suryanshsingh2001** [comment]
> Hello! I'd like to take on this task, can you please assign it to me?
@pchy-ynda  Sure, assigned the issue to you. Make sure to go through the checklist present in the issue. Feel free to add any other sections left.
